apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-java-ref-app-configmap
  {{- $filename :=  print "application-" .Values.configuration.env ".yml" }}
data:
  application.yml: |-
    {{.Files.Get $filename | nindent 4}}