{{- if .Values.service.exposed -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.service.name }}-route
  labels:
    {{- include "java-ref-app.labels" . | nindent 4 }}
spec:
  host: {{ .Values.service.name }}-{{.Values.configuration.env}}.{{ .Values.service.routerCanonicalHostname }}
  to:
    kind: Service
    name: {{ .Values.service.name }}
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
status:
  ingress:
    - host: {{ .Values.service.name }}-sit.{{ .Values.service.routerCanonicalHostname }}
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
      wildcardPolicy: None
      routerCanonicalHostname: {{ .Values.service.routerCanonicalHostname }}
{{- end }}
